# Generated by Django 3.2.6 on 2022-11-17 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionmenacemodel',
            name='variable',
        ),
        migrations.AddField(
            model_name='distributionmenacemodel',
            name='tipo_variable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arbolsaf.variabletypemodel', verbose_name='Variable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variablemodel',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='categoria'),
        ),
    ]
