# Generated by Django 3.2.6 on 2022-12-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablemodel',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='variablemodel',
            name='referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arbolsaf.referencemodel', verbose_name='Referencia'),
        ),
    ]
