# Generated by Django 3.2.6 on 2022-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencemodel',
            options={'managed': True, 'verbose_name': 'Referencia', 'verbose_name_plural': 'Referencias'},
        ),
        migrations.AlterField(
            model_name='synonymousmodel',
            name='sinonimo',
            field=models.CharField(max_length=255, verbose_name='sinónimo'),
        ),
    ]
