# Generated by Django 3.2.6 on 2022-12-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0002_auto_20221206_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemodel',
            name='referencia',
            field=models.TextField(default=1, verbose_name='fuente'),
            preserve_default=False,
        ),
    ]
