# Generated by Django 3.2.6 on 2022-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0002_auto_20221130_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunittypemodel',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre'),
        ),
    ]
