# Generated by Django 3.2.6 on 2022-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0003_alter_referencemodel_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemodel',
            name='referencia',
            field=models.TextField(blank=True, null=True, verbose_name='fuente'),
        ),
    ]
