# Generated by Django 3.2.6 on 2022-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0003_alter_measureunittypemodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletypemodel',
            name='tipo_variables',
            field=models.CharField(blank=True, choices=[('numerico', 'Valor numérico'), ('texto', 'Valor texto'), ('rango', 'Rango'), ('cualitativo', 'Cualitativo'), ('boolean', 'Boolean')], max_length=50, null=True, verbose_name='tipo variable'),
        ),
    ]
