# Generated by Django 3.2.6 on 2022-12-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0004_alter_referencemodel_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableTypeFamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Familia tipo variable',
                'verbose_name_plural': 'Familias tipo variables',
                'db_table': 'arbolsaf_variable_type_family',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='variabletypemodel',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbolsaf.measureunittypemodel', verbose_name='Unidad medida'),
        ),
        migrations.AddField(
            model_name='variabletypemodel',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbolsaf.variabletypefamilymodel', verbose_name='Familia'),
        ),
    ]
