# Generated by Django 3.2.6 on 2022-12-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0004_alter_variabletypemodel_tipo_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletypemodel',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arbolsaf.measureunittypemodel', verbose_name='Unidad medida'),
        ),
    ]
