# Generated by Django 3.2.6 on 2022-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0005_alter_variabletypemodel_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletypemodel',
            name='niveles_categoricos',
            field=models.TextField(verbose_name='Niveles categóricos'),
        ),
    ]
