# Generated by Django 3.2.6 on 2022-12-15 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbolsaf', '0005_auto_20221215_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletypefamilymodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variabletypefamilymodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='variabletypefamilymodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificado'),
        ),
        migrations.AddField(
            model_name='variabletypefamilymodel',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
