# Generated by Django 3.2.6 on 2022-12-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0006_auto_20221215_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletypefamilymodel',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
    ]
