# Generated by Django 3.2.6 on 2022-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0006_alter_variabletypemodel_niveles_categoricos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletypemodel',
            name='variable',
            field=models.CharField(max_length=255, verbose_name='variable'),
        ),
    ]
