# Generated by Django 3.2.6 on 2022-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0007_alter_variabletypemodel_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmodel',
            name='cod_esp',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código especie'),
        ),
    ]
