# Generated by Django 3.2.6 on 2022-12-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0008_alter_speciesmodel_cod_esp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablemodel',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='variablemodel',
            name='valor_numerico',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor numérico'),
        ),
        migrations.AddField(
            model_name='variablemodel',
            name='valor_texto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor texto'),
        ),
    ]
