# Generated by Django 3.2.6 on 2023-04-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0008_variablemodel_chequeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemodel',
            name='fuente_final',
            field=models.CharField(max_length=255, verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='referencemodel',
            name='referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='variabletypemodel',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbolsaf.variabletypefamilymodel', verbose_name='Grupo'),
        ),
    ]
