# Generated by Django 3.2.6 on 2022-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0009_auto_20221203_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablemodel',
            name='valor_boolean',
            field=models.BooleanField(default=False, verbose_name='Verdadero?'),
        ),
    ]
