# Generated by Django 3.2.6 on 2023-04-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0010_variabletypeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablemodel',
            name='valor_cualitativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arbolsaf.variabletypeoption', verbose_name='Valor cualitativo'),
        ),
    ]
