# Generated by Django 3.2.6 on 2023-04-29 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0011_variablemodel_valor_cualitativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablemodel',
            name='referencia_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='arbolsaf.referencemodel', verbose_name='Repetir referencia'),
        ),
    ]
