# Generated by Django 3.2.6 on 2023-05-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0012_variablemodel_referencia_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variabletypefamilymodel',
            options={'managed': True, 'verbose_name': 'Grupo de variable', 'verbose_name_plural': 'Grupos de variables'},
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='taxonid_wfo',
            field=models.URLField(max_length=50, verbose_name='Taxon ID WFO'),
        ),
    ]
