# Generated by Django 3.2.6 on 2023-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0013_auto_20230502_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmodel',
            name='taxonid_wfo',
            field=models.CharField(max_length=50, verbose_name='Taxon ID WFO'),
        ),
    ]
