# Generated by Django 3.2.6 on 2023-06-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0016_auto_20230616_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesmodel',
            options={'managed': True, 'ordering': ['nombre_comun'], 'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterModelOptions(
            name='variabletypemodel',
            options={'managed': True, 'ordering': ['variable'], 'verbose_name': 'Tipo de variable', 'verbose_name_plural': 'Tipos de variable'},
        ),
        migrations.RemoveField(
            model_name='variablemodel',
            name='categoria',
        ),
    ]
