# Generated by Django 3.2.6 on 2023-06-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0018_variablemodel_valores_cualitativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablemodel',
            name='valores_cualitativos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_arbolsaf_variablemodel_valores_cualitativos_+', to='arbolsaf.VariableTypeOption', verbose_name='Valores cualitativos'),
        ),
    ]
