# Generated by Django 3.2.6 on 2023-06-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0019_alter_variablemodel_valores_cualitativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletypemodel',
            name='seleccion_multiple',
            field=models.BooleanField(default=False, verbose_name='Es selección múltiple? (Aplicable solo a variables cualitativas)'),
        ),
    ]
