# Generated by Django 3.2.6 on 2023-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0022_alter_speciesmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_madera',
            field=models.IntegerField(default=0, editable=False, verbose_name='Total alimentos vacas'),
        ),
    ]
