# Generated by Django 3.2.6 on 2023-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0023_speciesmodel_valor_madera'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_biodiversidad',
            field=models.IntegerField(default=0, editable=False, verbose_name='Valor para Biodiversidad'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_biodiversidad_category',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='ninguno', editable=False, max_length=50, verbose_name='Valor para Biodiversidad'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_fruta',
            field=models.IntegerField(default=0, editable=False, verbose_name='Valor para  Fruta'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_fruta_category',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='ninguno', editable=False, max_length=50, verbose_name='Valor para Fruta'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_madera_category',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='ninguno', editable=False, max_length=50, verbose_name='Valor para Madera'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_microclima',
            field=models.IntegerField(default=0, editable=False, verbose_name='Valor para Microclima'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_microclima_category',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='ninguno', editable=False, max_length=50, verbose_name='Valor para Microclima'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_otros_usos',
            field=models.IntegerField(default=0, editable=False, verbose_name='Valor para Otros usos'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_otros_usos_category',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='ninguno', editable=False, max_length=50, verbose_name='Valor para otros Usos'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_suelo',
            field=models.IntegerField(default=0, editable=False, verbose_name='Valor para el Suelo'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='valor_suelo_category',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='ninguno', editable=False, max_length=50, verbose_name='Valor para Suelo'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='valor_madera',
            field=models.IntegerField(default=0, editable=False, verbose_name='Valor para  Madera'),
        ),
    ]
