# Generated by Django 3.2.6 on 2023-07-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0024_auto_20230629_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='indice_multiuso',
            field=models.FloatField(default=0.0, editable=False, verbose_name="'Indice Multiuso"),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='indice_valor_uso_relativo',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Indice de valor de uso relativo'),
        ),
        migrations.AddField(
            model_name='speciesmodel',
            name='ivim',
            field=models.FloatField(default=0.0, editable=False, verbose_name='IVIM'),
        ),
    ]
