# Generated by Django 3.2.6 on 2023-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0026_auto_20230705_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablemodel',
            name='valores_cualitativos',
            field=models.ManyToManyField(blank=True, null=True, to='arbolsaf.VariableTypeOption', verbose_name='Valores cualitativos'),
        ),
    ]
