# Generated by Django 3.2.6 on 2023-08-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0027_alter_variablemodel_valores_cualitativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
    ]
