# Generated by Django 3.2.6 on 2023-08-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0028_speciesmodel_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='link_cifor_icraf',
            field=models.URLField(blank=True, null=True, verbose_name='Link CIFOR-ICRAF'),
        ),
    ]
