# Generated by Django 3.2.6 on 2023-08-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0029_speciesmodel_link_cifor_icraf'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_especie', verbose_name='Imagen'),
        ),
    ]
