# Generated by Django 3.2.6 on 2023-08-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0030_speciesmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_especie', verbose_name='Imagen'),
        ),
    ]
