# Generated by Django 3.2.6 on 2023-08-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0033_auto_20230824_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesAdminModel',
            fields=[
            ],
            options={
                'verbose_name': 'Categorización Especies',
                'verbose_name_plural': 'Categorización Especies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('arbolsaf.speciesmodel',),
        ),
        migrations.RemoveField(
            model_name='speciesmodel',
            name='link_cifor_icraf',
        ),
    ]
