# Generated by Django 3.2.6 on 2023-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0035_auto_20230825_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagespecies',
            options={'managed': True, 'verbose_name': 'Imagen Especie', 'verbose_name_plural': 'Imágenes Especies'},
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='entidad_modificada',
            field=models.CharField(choices=[('general', 'General'), ('especie', 'Especie'), ('variable', 'Variable')], max_length=50, verbose_name='Entidad'),
        ),
    ]
