# Generated by Django 3.2.6 on 2023-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0037_alter_speciesmodel_taxonid_wfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmodel',
            name='taxonid_wfo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Taxón ID WFO'),
        ),
    ]
