# Generated by Django 3.2.6 on 2023-09-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0039_alter_variabletypemodel_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletypeoption',
            name='tipo_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arbolsaf.variabletypemodel', verbose_name='Tipo de Variable'),
        ),
    ]
