# Generated by Django 3.2.6 on 2023-11-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0040_alter_variabletypeoption_tipo_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='habilitada_herramienta',
            field=models.BooleanField(default=False, verbose_name='Habilitada en herramienta'),
        ),
    ]
