# Generated by Django 3.2.6 on 2023-11-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0041_speciesmodel_habilitada_herramienta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroReporteHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha reporte')),
                ('nombre_productor', models.CharField(max_length=255, verbose_name='Nombre del productor')),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=50, verbose_name='Distrito')),
                ('tipo_intervencion', models.CharField(max_length=50, verbose_name='Tipo de intervención')),
                ('finca_ha', models.IntegerField(verbose_name='Tamaño de la finca (ha)')),
                ('parcela_ha', models.IntegerField(verbose_name='Tamaño de la parcela (ha)')),
                ('tipo_usuario', models.CharField(max_length=50, verbose_name='Tipo de usuario')),
                ('identidad_genero', models.CharField(max_length=50, verbose_name='Identidad de género')),
                ('edad_usuario', models.CharField(max_length=50, verbose_name='Edad del usuario')),
                ('especies_str', models.TextField(verbose_name='Especies')),
                ('especies', models.ManyToManyField(to='arbolsaf.SpeciesModel', verbose_name='Especies')),
            ],
            options={
                'verbose_name': 'Registro reporte herramienta',
                'verbose_name_plural': 'Registros reporte herramienta',
                'db_table': 'arbolsaf_registro_reporte',
                'managed': True,
            },
        ),
    ]
