# Generated by Django 3.2.6 on 2023-11-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0042_registroreporteherramienta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='distrito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='edad_usuario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Edad del usuario'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='especies_str',
            field=models.TextField(blank=True, null=True, verbose_name='Especies'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='finca_ha',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tamaño de la finca (ha)'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='identidad_genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identidad de género'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='parcela_ha',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tamaño de la parcela (ha)'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='tipo_intervencion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de intervención'),
        ),
        migrations.AlterField(
            model_name='registroreporteherramienta',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
