# Generated by Django 3.2.6 on 2023-11-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0044_auto_20231123_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(default='Configuración', max_length=50, verbose_name='Nombre'),
        ),
    ]
