# Generated by Django 3.2.6 on 2023-12-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0046_alter_configuracion_texto_seccion_agradecimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletypemodel',
            name='uso_herramienta',
            field=models.BooleanField(default=False, verbose_name='Utilizada en herramienta'),
        ),
    ]
