# Generated by Django 3.2.6 on 2026-06-12 17:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0053_versiones_merge_and_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='texto_metodos_categorizacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Métodos: Categorización & IVIM'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='texto_metodos_datos',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Métodos: Datos y referencias (texto introductorio)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='texto_metodos_seleccion',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Métodos: Selección de especies'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='texto_metodos_versiones',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Métodos: Versiones y créditos'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='texto_seccion_arbolsaf',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='texto_seccion_descargo_responsabilidad',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Métodos: Descargo de responsabilidad'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='valor_biodiversidad',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Valor para Biodiversidad'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='valor_otros_usos',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Valor para Otros usos'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='valor_suelo',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Valor para el Suelo'),
        ),
    ]
