# Generated by Django 3.2.6 on 2026-06-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbolsaf', '0054_ckeditor_uploading_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='texto_seccion_agradecimientos',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='texto_seccion_creditos',
        ),
    ]
